# Docker and Maven
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- cicd
- prod

variables:
  imageRepository: 'credential-management-service'
  tag: '$(Build.BuildNumber)'
  registryConnection: 'FlashDevOps ACRConnection'

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Build and push Docker Image
  inputs:
    containerRegistry: '$(registryConnection)'
    repository: '$(imageRepository)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(tag)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'docker-compose.yml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Publish/'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Publish/'
    ArtifactName: 'compose_file'
    publishLocation: 'Container'
