version: "3.2"
services:
  rabbit:
    image: "rabbitmq:3.6.6-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
      - ":"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
  web:
    image: nginx
    volumes:----------------
      - C:\etc\docker-conf\nginx\nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
